# Generated by Django 6.0.1 on 2026-01-31 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_invited_alter_user_name_membership'),
        ('company', '0002_designationgroup_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.designation'),
        ),
    ]
