# Generated by Django 6.0.1 on 2026-03-07 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_employeeweekend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeweekend',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekend_override', to=settings.AUTH_USER_MODEL),
        ),
    ]
