# Generated by Django 6.0.1 on 2026-02-01 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('business_categories', models.JSONField(blank=True, default=list)),
                ('selling_products', models.JSONField(blank=True, default=list)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.district')),
                ('division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.division')),
                ('post_office', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.postoffice')),
                ('thana', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.thana')),
            ],
        ),
    ]
