# Generated by Django 6.0.1 on 2026-02-01 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_designationgroup_designation'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='business_categories',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='selling_products',
        ),
        migrations.CreateModel(
            name='BusinessCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='SellingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='business_categories',
            field=models.ManyToManyField(blank=True, to='customers.businesscategory'),
        ),
        migrations.AddField(
            model_name='customer',
            name='selling_products',
            field=models.ManyToManyField(blank=True, to='customers.sellingproduct'),
        ),
    ]
