# Generated by Django 6.0.1 on 2026-03-03 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_designationgroup_designation'),
        ('customers', '0005_alter_customer_company'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('company', 'phone')},
        ),
    ]
