# Generated by Django 6.0.1 on 2026-03-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitreport',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='visitreport',
            name='note',
        ),
        migrations.AddField(
            model_name='visitreport',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
