# Generated by Django 6.0.1 on 2026-03-06 14:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_visitreport_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitreport',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('checked_in', 'Checked In'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
