# Generated by Django 6.0.1 on 2026-03-04 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_assign_date_alter_collection_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='points',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('approved', 'Approved')], default='pending', max_length=20),
        ),
    ]
