# Generated by Django 6.0.1 on 2026-03-06 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_employeelocation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisitReport',
        ),
    ]
