# Generated by Django 6.0.1 on 2026-03-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_delete_visitreport'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='employeelocation',
            name='tasks_emplo_employe_8e06c7_idx',
        ),
        migrations.RemoveIndex(
            model_name='employeelocation',
            name='tasks_emplo_updated_ccd6bc_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='tasks_task_company_4e1a1e_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='tasks_task_created_be1ba2_idx',
        ),
        migrations.RemoveIndex(
            model_name='taskassignment',
            name='tasks_taska_employe_1dbad2_idx',
        ),
        migrations.RemoveIndex(
            model_name='taskassignment',
            name='tasks_taska_status_6a8bf4_idx',
        ),
        migrations.RemoveIndex(
            model_name='taskassignment',
            name='tasks_taska_employe_8cb7a3_idx',
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='reject_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='resubmit_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
