# Generated by Django 6.0.1 on 2026-03-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_remove_employeelocation_tasks_emplo_employe_8e06c7_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='task',
            name='next_run',
            field=models.DateField(blank=True, help_text='Next date this task will auto appear', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='repeat_type',
            field=models.CharField(choices=[('none', 'One Time'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('15days', 'Every 15 Days'), ('monthly', 'Monthly')], default='none', max_length=20),
        ),
    ]
