# Generated by Django 6.0.1 on 2026-03-05 17:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_designationgroup_designation'),
        ('customers', '0006_alter_customer_unique_together'),
        ('tasks', '0006_remove_task_points_task_approved_at_task_approved_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='task',
            name='tasks_task_due_dat_bce847_idx',
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='custom_points',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['company', 'status'], name='tasks_task_company_c23f28_idx'),
        ),
    ]
