# Generated by Django 6.0.1 on 2026-03-07 22:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_task_is_active_task_next_run_task_repeat_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassignment',
            name='assignment_date',
            field=models.DateField(default=datetime.date(2026, 3, 8)),
            preserve_default=False,
        ),
    ]
