# Generated by Django 6.0.1 on 2026-03-08 00:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_taskassignment_assignment_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskassignment',
            unique_together={('task', 'employee', 'assignment_date')},
        ),
    ]
