# Generated by Django 6.0.1 on 2026-03-08 13:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_taskassignment_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskassignment',
            options={'ordering': ['-assignment_date', '-created_at']},
        ),
        migrations.AddIndex(
            model_name='taskassignment',
            index=models.Index(fields=['employee', 'assignment_date'], name='tasks_taska_employe_5d92ab_idx'),
        ),
        migrations.AddIndex(
            model_name='taskassignment',
            index=models.Index(fields=['task', 'assignment_date'], name='tasks_taska_task_id_6f9a28_idx'),
        ),
        migrations.AddIndex(
            model_name='taskassignment',
            index=models.Index(fields=['status', 'assignment_date'], name='tasks_taska_status_0d3a28_idx'),
        ),
    ]
