# Generated by Django 6.0.1 on 2026-03-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_taskactionnote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assign_date',
        ),
        migrations.AddField(
            model_name='task',
            name='assign_time',
            field=models.TimeField(blank=True, help_text='Time when task should appear', null=True),
        ),
    ]
