# Generated by Django 6.0.1 on 2026-03-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_remove_task_assign_date_task_assign_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassignment',
            name='description_override',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='due_date_override',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='priority_override',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='task_type_override',
            field=models.CharField(blank=True, choices=[('visit', 'Visit'), ('desk', 'Desk Work'), ('call', 'Call'), ('meeting', 'Meeting'), ('collection', 'Collection')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='title_override',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
