# Generated by Django 6.0.1 on 2026-03-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_taskassignment_description_override_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassignment',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='checkin_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='checkin_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskactionnote',
            name='note_type',
            field=models.CharField(choices=[('reject', 'Reject'), ('resubmit', 'Resubmit'), ('comment', 'Comment')], max_length=10),
        ),
    ]
