# Generated by Django 6.0.1 on 2026-03-08 06:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_companyholiday_companyweekend'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyholiday',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='companyholiday',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companyholiday',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AddConstraint(
            model_name='companyholiday',
            constraint=models.UniqueConstraint(fields=('company', 'date'), name='unique_company_holiday'),
        ),
    ]
