# Generated by Django 6.0.1 on 2026-03-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_companyholiday_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyholiday',
            options={'ordering': ['date']},
        ),
        migrations.RenameField(
            model_name='companyholiday',
            old_name='end_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='companyholiday',
            name='start_date',
        ),
        migrations.AddConstraint(
            model_name='companyholiday',
            constraint=models.UniqueConstraint(fields=('company', 'date'), name='unique_company_holiday'),
        ),
    ]
