# Generated by Django 6.0.1 on 2026-03-08 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_companyholiday_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyholiday',
            options={'ordering': ['start_date']},
        ),
        migrations.RemoveConstraint(
            model_name='companyholiday',
            name='unique_company_holiday',
        ),
        migrations.RenameField(
            model_name='companyholiday',
            old_name='date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='companyholiday',
            name='start_date',
            field=models.DateField(db_index=True, default=datetime.date(2026, 3, 8)),
            preserve_default=False,
        ),
    ]
