# Generated by Django 6.0.1 on 2026-03-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_alter_companyholiday_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_setup_complete',
            field=models.BooleanField(default=False),
        ),
    ]
